### ISSUE TITLE
Compatibility issue with TYPO3 7.4 regarding property "showitem" in TCA of recipientlist

### ISSUE THREAD

**Issue by dscoding** [Ecodev/newsletter#72]
Hi
The use of the property showitem has changed in TYPO3 7.3 and again in in 7.4: https://docs.typo3.org/typo3cms/TCAReference/Reference/Types/Index.html

With the current version of newsletter and TYPO3 7.4 it is not possible to open and edit the recipient lists. To make it compatible it is sufficient to change the RecipientList.php:

    'types' => array(
        '0' => array('showitem' => 'hidden;;1, title, type'),
        'Ecodev\\Newsletter\\Domain\\Model\\RecipientList\\BeUsers' => array('showitem' => 'hidden;;1, title, plain_only, lang, type, be_users, recipients_preview'),
        'Ecodev\\Newsletter\\Domain\\Model\\RecipientList\\FeGroups' => array('showitem' => 'hidden;;1, title, plain_only, lang, type, fe_groups, recipients_preview'),
        'Ecodev\\Newsletter\\Domain\\Model\\RecipientList\\FePages' => array('showitem' => 'hidden;;1, title, plain_only, lang, type, fe_pages, recipients_preview'),
        'Ecodev\\Newsletter\\Domain\\Model\\RecipientList\\Sql' => array('showitem' => 'hidden;;1, title, plain_only, type, sql_statement, sql_register_bounce, sql_register_open, sql_register_click, recipients_preview'),
        'Ecodev\\Newsletter\\Domain\\Model\\RecipientList\\CsvFile' => array('showitem' => 'hidden;;1, title, plain_only, type, csv_separator, csv_fields, csv_filename, recipients_preview'),
        'Ecodev\\Newsletter\\Domain\\Model\\RecipientList\\CsvList' => array('showitem' => 'hidden;;1, title, plain_only, type, csv_separator, csv_fields, csv_values, recipients_preview'),
        'Ecodev\\Newsletter\\Domain\\Model\\RecipientList\\CsvUrl' => array('showitem' => 'hidden;;1, title, plain_only, type, csv_separator, csv_fields, csv_url, recipients_preview'),
        'Ecodev\\Newsletter\\Domain\\Model\\RecipientList\\Html' => array('showitem' => 'hidden;;1, title, plain_only, lang, type, html_url, html_fetch_type, recipients_preview'),
    ),

Please note that I did not test this is TYPO3 6.2.

Best.

**Comment by MoppieMop** [comment]
In TYPO3 6.2.15 I can not open hidden recipient lists. So I assume this not only a TYPO3 7.4 problem.

**Comment by PowerKiKi** [comment]
That was actually two different issues. Both are fixed in 2.5.3

**Comment by siwa-pparzer** [comment]
Bug still exists:
TYPO3: 7.6.11
newsletter: 2.6.1

TYPO3 Error Message:
"The page did not exist or was inaccessible. Reason: ID was not an accessible page"

When I alter the TCA of the recipient list for example:
``'types' => array(
        '0' => array('showitem' => 'hidden;;1, title, type'),
    ),``
it works

also tried Version 3.1.0 -> blank page

**Comment by PowerKiKi** [comment]
@siwa-pparzer, I can't reproduce on a brand new TYPO3 7.6.11, Newsletter 3.1.0 and PHP 7.0.11. RecipientList are displayed and editable as expected. If you still experience issues, please open a new issue including more details (error message and so on).
